version: '3.8'

services:
  clash-config-merge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    command: --url 'https://example.com/clash'
    restart: unless-stopped
    volumes:
      - ./clash.yaml:/app/clash.yaml:ro  # 可选: 挂载本地的clash.yaml文件（非必须） 